### ISSUE TITLE
Generate Rotation without Starting With user in Users causes failure

### ISSUE THREAD

**Issue by mboneil10** [umts/screaming-dinosaur#69] opened 2017-04-26 15:56 UTC
I selected a name for `Starting With` that was not in `Users.` I clicked the button to generate a rotation and something went wrong. It would be helpful if I was given a reason for this failure.

**Comment by dfaulken** [comment] 2017-04-26 21:37
This *particular* failure was resolved in https://github.com/umts/screaming-dinosaur/commit/d41839b2776704f9aa44db7ddf8bb2b1398b9fbd, but in general exceptions caused by [the `create!` call](https://github.com/umts/screaming-dinosaur/commit/4e95b5057ec9d53cadd9c89e5638829bcd317d10#diff-b6ee507011c5b6dee36105e726df3f62R12) in that model method will just cause a 500.

Perhaps tricky to do given where the code lives, but it'd be nice if errors could bubble up somehow, or if we could at least do better date validation beforehand.

**Comment by mboneil10** [comment] 2017-04-27 17:48
I'm not sure we're thinking of the same instance. If I have this as an input
<img width="866" alt="screen shot 2017-04-27 at 1 46 08 pm" src="https://cloud.githubusercontent.com/assets/19267771/25496696/e8278d2c-2b4f-11e7-9da3-6bdcabcb83e7.png">
then I'll receive a failure. But yeah, still a 500.

**Comment by dfaulken** [comment] 2017-04-27 18:25
Ah, I see! You're completely right. My bad.

**Closed** 2017-05-02 17:45 UTC
